import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { cliInvocation } from './windows-agents.mjs';

const run = promisify(execFile);
export const psLiteral = (text) => `'${String(text).replaceAll("'", "''")}'`;
export const encodedScript = (text) => Buffer.from(text, 'utf16le').toString('base64');

export async function pickWindowsFolder() {
  const script = `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
Add-Type -AssemblyName System.Windows.Forms
$picker = New-Object System.Windows.Forms.FolderBrowserDialog
$picker.Description = 'AI Council - select a project folder'
$picker.ShowNewFolderButton = $false
try { if ($picker.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { [Console]::Write($picker.SelectedPath) } }
finally { $picker.Dispose() }`;
  const result = await run('powershell.exe', ['-NoProfile', '-STA', '-EncodedCommand', encodedScript(script)], {
    windowsHide: true, timeout: 300000, maxBuffer: 100000, encoding: 'utf8',
  });
  return result.stdout.trim().replace(/^\uFEFF/, '');
}

export function openWindowsLogin(key, binaries) {
  const operations = { claude: ['claude', ['auth', 'login', '--claudeai']], codex: ['codex', ['login']], gemini: ['agy', ['models']] };
  if (!operations[key]) throw new Error('Unknown model.');
  const [name, args] = operations[key];
  const invocation = cliInvocation(binaries[name], args);
  const script = `Write-Host 'AI Council - ${name} sign-in'
& ${psLiteral(invocation.command)} ${invocation.args.map(psLiteral).join(' ')}
if ($LASTEXITCODE -eq 0) { Write-Host 'Return to AI Council to refresh status.' }
else { Write-Host 'Sign-in did not complete. Check the error above.' }`;
  return new Promise((resolve, reject) => {
    const child = spawn('powershell.exe', ['-NoProfile', '-NoExit', '-EncodedCommand', encodedScript(script)], {
      detached: true, windowsHide: false, stdio: 'ignore',
    });
    child.once('error', reject);
    child.once('spawn', () => { child.unref(); resolve(); });
  });
}

export function openWindowsBrowser(url) {
  // The URL is generated by the server, never received from a client request.
  const child = spawn('rundll32.exe', ['url.dll,FileProtocolHandler', url], { windowsHide: true, stdio: 'ignore' });
  child.on('error', () => { console.error('Open the local URL printed above in your browser.'); });
}
